import React, { useState, useEffect } from 'react';
import { startOfMonth, endOfMonth, format, isSameDay, addMonths, subMonths, getYear, getMonth, setDate, addDays, isBefore } from 'date-fns';
import { Transaction, Category, Profile, FixedItem, SettingsTab } from './types';
import { DEFAULT_EXPENSE_CATEGORIES, DEFAULT_INCOME_CATEGORIES, DEFAULT_PROFILES } from './constants';
import { generateId, getMonthKey } from './utils';
import Calendar from './components/Calendar';
import BottomBar, { BottomTab } from './components/BottomBar';
import Settings from './components/Settings';
import Statistics from './components/Statistics';
import TransactionForm from './components/TransactionForm';
import TransactionDetails from './components/TransactionDetails';
import { Plus } from 'lucide-react';

const App: React.FC = () => {
  // --- State (기존 유지) ---
  const [currentDate, setCurrentDate] = useState(new Date());
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [fixedItems, setFixedItems] = useState<FixedItem[]>([]);
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);
  const [activeSettingsTab, setActiveSettingsTab] = useState<SettingsTab | null>(null);
  const [isTransactionFormOpen, setIsTransactionFormOpen] = useState(false);

  // --- Persistence (기존 유지) ---
  useEffect(() => {
    const loadData = () => {
      const storedTransactions = localStorage.getItem('calcbook_transactions');
      const storedCategories = localStorage.getItem('calcbook_categories');
      const storedProfiles = localStorage.getItem('calcbook_profiles');
      const storedFixedItems = localStorage.getItem('calcbook_fixed');
      if (storedTransactions) setTransactions(JSON.parse(storedTransactions));
      if (storedCategories) setCategories(JSON.parse(storedCategories));
      else setCategories([...DEFAULT_INCOME_CATEGORIES, ...DEFAULT_EXPENSE_CATEGORIES]);
      if (storedProfiles) setProfiles(JSON.parse(storedProfiles));
      else setProfiles(DEFAULT_PROFILES);
      if (storedFixedItems) setFixedItems(JSON.parse(storedFixedItems));
    };
    loadData();
  }, []);

  useEffect(() => { localStorage.setItem('calcbook_transactions', JSON.stringify(transactions)); }, [transactions]);
  useEffect(() => { localStorage.setItem('calcbook_categories', JSON.stringify(categories)); }, [categories]);
  useEffect(() => { localStorage.setItem('calcbook_profiles', JSON.stringify(profiles)); }, [profiles]);
  useEffect(() => { localStorage.setItem('calcbook_fixed', JSON.stringify(fixedItems)); }, [fixedItems]);

  // --- Fixed Item Logic (기존 유지) ---
  useEffect(() => {
    setTransactions(currentTransactions => {
      const today = new Date();
      const daysInMonth = endOfMonth(today).getDate();
      const newTransactions: Transaction[] = [];
      fixedItems.forEach(item => {
        const targetDay = Math.min(item.day, daysInMonth);
        const targetDate = setDate(today, targetDay);
        const dateStr = format(targetDate, 'yyyy-MM-dd');
        const exists = currentTransactions.some(t => t.isFixedAutoGenerated && t.date === dateStr && t.amount === item.amount && t.categoryId === item.categoryId && t.type === item.type);
        if (!exists) {
          newTransactions.push({ id: generateId(), amount: item.amount, date: dateStr, categoryId: item.categoryId, profileId: item.profileId, memo: item.memo, type: item.type, isFixedAutoGenerated: true });
        }
      });
      return newTransactions.length > 0 ? [...currentTransactions, ...newTransactions] : currentTransactions;
    });
  }, [fixedItems]);

  // --- Handlers ---
  const handleDateClick = (date: Date) => {
    if (selectedDate && isSameDay(selectedDate, date)) setSelectedDate(null);
    else setSelectedDate(date);
  };
  const handlePrevMonth = () => setCurrentDate(subMonths(currentDate, 1));
  const handleNextMonth = () => setCurrentDate(addMonths(currentDate, 1));
  const handleAddTransaction = (newTx: Omit<Transaction, 'id'>) => {
    setTransactions(prev => [...prev, { ...newTx, id: generateId() }]);
    setIsTransactionFormOpen(false);
  };
  const handleDeleteTransaction = (id: string) => setTransactions(prev => prev.filter(t => t.id !== id));
  const handleTabClick = (tab: BottomTab) => tab === 'CALENDAR' ? setActiveSettingsTab(null) : setActiveSettingsTab(tab);

  const getMonthBalance = (date: Date) => {
    const endOfViewMonth = endOfMonth(date);
    let balance = 0;
    transactions.forEach(t => {
       if (isBefore(new Date(t.date), addDays(endOfViewMonth, 1))) {
         if (t.type === 'INCOME') balance += t.amount;
         else balance -= t.amount;
       }
    });
    return balance;
  };

  const isDetailsOpen = !!(selectedDate && transactions.some(t => t.date === format(selectedDate, 'yyyy-MM-dd')));

  const renderHeader = () => {
    if (activeSettingsTab) return null;
    return (
      <header className="flex-none px-6 pt-10 pb-6 bg-black text-white flex justify-between items-end z-10 rounded-b-[2.5rem] shadow-xl min-h-[130px] box-border w-full">
        <div className="flex flex-col gap-1">
          <span className="text-xs font-medium tracking-wider text-gray-400 font-round">{getYear(currentDate)}</span>
          <div className="flex items-center gap-4 mt-1">
             <button onClick={handlePrevMonth} className="text-2xl font-round p-1">{'<'}</button>
             <h1 className="text-3xl font-round font-bold">{getMonth(currentDate) + 1}월</h1>
             <button onClick={handleNextMonth} className="text-2xl font-round p-1">{'>'}</button>
          </div>
        </div>
        <div className="text-right pb-1">
          <p className="text-[10px] text-gray-400 font-round opacity-80">총 잔액</p>
          <p className="text-xl font-round font-bold">{getMonthBalance(currentDate).toLocaleString()} <span className="text-xs font-normal text-gray-500">₩</span></p>
        </div>
      </header>
    );
  };

  return (
    /* w-screen과 overflow-x-hidden을 주어 가로 밀림을 강제로 방지합니다. */
    <div className="flex flex-col w-screen max-w-md mx-auto bg-white overflow-x-hidden relative shadow-2xl" style={{ height: 'calc(var(--vh, 1vh) * 100)' }}>
      {renderHeader()}

      <main className="flex-1 overflow-y-auto overflow-x-hidden bg-white pb-28 touch-pan-y relative w-full">
        {activeSettingsTab === 'STATISTICS' ? (
          <Statistics currentDate={currentDate} transactions={transactions} categories={categories} onPrevMonth={handlePrevMonth} onNextMonth={handleNextMonth} />
        ) : activeSettingsTab ? (
          <Settings tab={activeSettingsTab} onClose={() => setActiveSettingsTab(null)} categories={categories} setCategories={setCategories} profiles={profiles} setProfiles={setProfiles} fixedItems={fixedItems} setFixedItems={setFixedItems} />
        ) : (
          <Calendar currentDate={currentDate} transactions={transactions} selectedDate={selectedDate} onDateClick={handleDateClick} categories={categories} profiles={profiles} onDeleteTransaction={handleDeleteTransaction} onOpenAddForm={() => setIsTransactionFormOpen(true)} />
        )}
      </main>

      {/* 버튼 밀림 방지: left-auto, right-6을 사용하여 기기 오른쪽 끝에 고정합니다. */}
      {!activeSettingsTab && !isDetailsOpen && (
        <button 
          onClick={() => setIsTransactionFormOpen(true)}
          className="fixed bottom-24 right-6 w-14 h-14 bg-black rounded-full flex items-center justify-center text-white shadow-2xl z-40 active:scale-95 transition-all"
          style={{ right: 'max(1.5rem, calc((100vw - 28rem) / 2 + 1.5rem))' }}
        >
          <Plus size={28} />
        </button>
      )}

      <div className="flex-none bg-white border-t border-gray-100 z-50 w-full">
        <BottomBar activeTab={activeSettingsTab || 'CALENDAR'} onTabClick={handleTabClick} />
      </div>

      {isTransactionFormOpen && (
        <TransactionForm date={selectedDate || new Date()} categories={categories} profiles={profiles} onClose={() => setIsTransactionFormOpen(false)} onSubmit={handleAddTransaction} />
      )}

      {isDetailsOpen && selectedDate && (
        <div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/40 p-4">
          <div className="w-full max-w-md bg-white rounded-[2.5rem] p-4 shadow-2xl animate-in slide-in-from-bottom duration-300">
            <TransactionDetails
              date={selectedDate}
              transactions={transactions.filter(t => t.date === format(selectedDate, 'yyyy-MM-dd'))}
              categories={categories}
              profiles={profiles}
              onClose={() => setSelectedDate(null)}
              onDelete={handleDeleteTransaction}
              onAdd={() => setIsTransactionFormOpen(true)}
            />
          </div>
        </div>
      )}
    </div>
  );
};

export default App;
