import React, { useState, useEffect } from 'react';
import { startOfMonth, endOfMonth, format, isSameDay, addMonths, subMonths, getYear, getMonth, setDate, addDays, isBefore } from 'date-fns';
import { Transaction, Category, Profile, FixedItem, SettingsTab } from './types';
import { DEFAULT_EXPENSE_CATEGORIES, DEFAULT_INCOME_CATEGORIES, DEFAULT_PROFILES } from './constants';
import { generateId, getMonthKey } from './utils';
import Calendar from './components/Calendar';
import BottomBar, { BottomTab } from './components/BottomBar';
import Settings from './components/Settings';
import Statistics from './components/Statistics';
import TransactionForm from './components/TransactionForm';
import { Plus } from 'lucide-react';
import TransactionDetails from './components/TransactionDetails';
const App: React.FC = () => {
  // --- State ---
  const [currentDate, setCurrentDate] = useState(new Date());
  
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [fixedItems, setFixedItems] = useState<FixedItem[]>([]);
  
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);
  const [activeSettingsTab, setActiveSettingsTab] = useState<SettingsTab | null>(null);
  const [isTransactionFormOpen, setIsTransactionFormOpen] = useState(false);

  // --- Persistence ---
  useEffect(() => {
    const loadData = () => {
      const storedTransactions = localStorage.getItem('calcbook_transactions');
      const storedCategories = localStorage.getItem('calcbook_categories');
      const storedProfiles = localStorage.getItem('calcbook_profiles');
      const storedFixedItems = localStorage.getItem('calcbook_fixed');

      if (storedTransactions) setTransactions(JSON.parse(storedTransactions));
      
      if (storedCategories) {
        setCategories(JSON.parse(storedCategories));
      } else {
        setCategories([...DEFAULT_INCOME_CATEGORIES, ...DEFAULT_EXPENSE_CATEGORIES]);
      }

      if (storedProfiles) {
        setProfiles(JSON.parse(storedProfiles));
      } else {
        setProfiles(DEFAULT_PROFILES);
      }

      if (storedFixedItems) setFixedItems(JSON.parse(storedFixedItems));
    };
    loadData();
  }, []);

  useEffect(() => {
    localStorage.setItem('calcbook_transactions', JSON.stringify(transactions));
  }, [transactions]);

  useEffect(() => {
    localStorage.setItem('calcbook_categories', JSON.stringify(categories));
  }, [categories]);

  useEffect(() => {
    localStorage.setItem('calcbook_profiles', JSON.stringify(profiles));
  }, [profiles]);

  useEffect(() => {
    localStorage.setItem('calcbook_fixed', JSON.stringify(fixedItems));
  }, [fixedItems]);

  // --- Fixed Item Logic ---
  useEffect(() => {
    setTransactions(currentTransactions => {
      const today = new Date();
      const daysInMonth = endOfMonth(today).getDate();
      const newTransactions: Transaction[] = [];

      fixedItems.forEach(item => {
        const targetDay = Math.min(item.day, daysInMonth);
        const targetDate = setDate(today, targetDay);
        const dateStr = format(targetDate, 'yyyy-MM-dd');

        const exists = currentTransactions.some(t => 
          t.isFixedAutoGenerated && 
          t.date === dateStr && 
          t.amount === item.amount && 
          t.categoryId === item.categoryId &&
          t.type === item.type
        );

        if (!exists) {
          newTransactions.push({
            id: generateId(),
            amount: item.amount,
            date: dateStr,
            categoryId: item.categoryId,
            profileId: item.profileId,
            memo: item.memo,
            type: item.type,
            isFixedAutoGenerated: true,
          });
        }
      });

      if (newTransactions.length > 0) {
        return [...currentTransactions, ...newTransactions];
      }
      return currentTransactions;
    });
  }, [fixedItems]);


  // --- Handlers ---

  const handleDateClick = (date: Date) => {
    if (selectedDate && isSameDay(selectedDate, date)) {
      setSelectedDate(null);
    } else {
      setSelectedDate(date);
    }
  };

  const handlePrevMonth = () => setCurrentDate(subMonths(currentDate, 1));
  const handleNextMonth = () => setCurrentDate(addMonths(currentDate, 1));

  const handleAddTransaction = (newTx: Omit<Transaction, 'id'>) => {
    setTransactions(prev => [...prev, { ...newTx, id: generateId() }]);
    setIsTransactionFormOpen(false);
  };

  const handleDeleteTransaction = (id: string) => {
    setTransactions(prev => prev.filter(t => t.id !== id));
  };

  const handleTabClick = (tab: BottomTab) => {
    if (tab === 'CALENDAR') {
      setActiveSettingsTab(null);
    } else {
      setActiveSettingsTab(tab);
    }
  };

  const getMonthBalance = (date: Date) => {
    const endOfViewMonth = endOfMonth(date);
    let balance = 0;
    transactions.forEach(t => {
       if (isBefore(new Date(t.date), addDays(endOfViewMonth, 1))) {
         if (t.type === 'INCOME') balance += t.amount;
         else balance -= t.amount;
       }
    });
    return balance;
  };

  const isDetailsOpen = selectedDate && transactions.some(t => t.date === format(selectedDate, 'yyyy-MM-dd'));

  // --- Render Headers ---
  const renderHeader = () => {
    // Return null if we are in settings mode (User requested removal of black bar)
    if (activeSettingsTab) return null;

    // Calendar Header - Reduced height
    const headerBaseClass = "flex-none px-6 pt-8 pb-6 bg-black text-white flex justify-between items-end z-10 rounded-b-[2.5rem] shadow-xl min-h-[120px] box-border";

    return (
      <header className={headerBaseClass}>
        <div className="flex flex-col gap-1">
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium tracking-wider text-gray-400 font-round">{getYear(currentDate)}</span>
          </div>
          <div className="flex items-center gap-4 mt-1">
             <button onClick={handlePrevMonth} className="hover:text-gray-300 transition-colors text-2xl font-round">{'<'}</button>
             <h1 className="text-3xl font-round font-bold tracking-tight mb-1">{getMonth(currentDate) + 1}월</h1>
             <button onClick={handleNextMonth} className="hover:text-gray-300 transition-colors text-2xl font-round">{'>'}</button>
          </div>
        </div>
        <div className="text-right pb-1">
          <p className="text-[10px] text-gray-400 mb-0.5 font-round opacity-80">총 잔액</p>
          <p className="text-xl font-round font-bold tracking-tight">
            {getMonthBalance(currentDate).toLocaleString()} <span className="text-xs font-normal text-gray-500">KRW</span>
          </p>
        </div>
      </header>
    );
  };

  const renderContent = () => {
    if (activeSettingsTab === 'STATISTICS') {
      return (
        <Statistics 
          currentDate={currentDate}
          transactions={transactions}
          categories={categories}
          onPrevMonth={handlePrevMonth}
          onNextMonth={handleNextMonth}
        />
      );
    }

    if (activeSettingsTab) {
      return (
        <Settings 
          tab={activeSettingsTab}
          onClose={() => setActiveSettingsTab(null)}
          categories={categories}
          setCategories={setCategories}
          profiles={profiles}
          setProfiles={setProfiles}
          fixedItems={fixedItems}
          setFixedItems={setFixedItems}
        />
      );
    }

    return (
      <Calendar 
        currentDate={currentDate} 
        transactions={transactions}
        selectedDate={selectedDate}
        onDateClick={handleDateClick}
        categories={categories}
        profiles={profiles}
        onDeleteTransaction={handleDeleteTransaction}
        onOpenAddForm={() => setIsTransactionFormOpen(true)}
      />
    );
  };

  return (
    <div className="flex flex-col h-full bg-white sm:rounded-[2rem] sm:border-8 sm:border-gray-200 overflow-hidden relative shadow-2xl">
      
      {renderHeader()}

      {/* Main Content Area */}
      <main className="flex-1 overflow-y-auto relative bg-white">
        {renderContent()}
      </main>

      {/* Floating Action Button - Only on Calendar */}
      {!activeSettingsTab && !isDetailsOpen && (
        <button 
          onClick={() => setIsTransactionFormOpen(true)}
          className="absolute bottom-24 right-6 w-14 h-14 bg-black rounded-full flex items-center justify-center text-white shadow-xl hover:scale-105 active:scale-95 transition-all z-20"
        >
          <Plus size={28} />
        </button>
      )}

      {/* Bottom Settings Bar */}
      <BottomBar 
        activeTab={activeSettingsTab || 'CALENDAR'}
        onTabClick={handleTabClick} 
      />

      {/* Add Transaction Modal */}
      {isTransactionFormOpen && (
        <TransactionForm 
          date={selectedDate || new Date()}
          categories={categories}
          profiles={profiles}
          onClose={() => setIsTransactionFormOpen(false)}
          onSubmit={handleAddTransaction}
        />
      )}

    </div>
  );
};

export default App;
