export type TransactionType = 'INCOME' | 'EXPENSE';

export interface Category {
  id: string;
  name: string;
  type: TransactionType;
  isDefault?: boolean; // Default categories cannot be deleted, but requirements say parent types can't be edited, subs can.
}

export interface Profile {
  id: string;
  name: string;
  color: string;
  image?: string | null; // Base64 data URL
}

export interface Transaction {
  id: string;
  amount: number;
  date: string; // ISO Date string YYYY-MM-DD
  categoryId: string;
  profileId: string;
  memo: string;
  type: TransactionType;
  isFixedAutoGenerated?: boolean;
}

export interface FixedItem {
  id: string;
  day: number; // 1-31, 32 = Last Day (End of Month)
  amount: number;
  categoryId: string;
  profileId: string;
  memo: string;
  type: TransactionType;
}

export type ViewMode = 'MONTH' | 'WEEK';

export const PARENT_CATEGORIES = {
  INCOME: '수입',
  EXPENSE: '지출',
};

export type SettingsTab = 'CATEGORY' | 'FIXED' | 'PROFILE' | 'STATISTICS';